include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: univention/dist/docker-services
    file:
      - kaniko.yml
      - pre-commit.yml

variables:
  LANG: "C.UTF-8"
  DEBIAN_FRONTEND: noninteractive

tox:
  image: docker-registry.knut.univention.de/phahn/ucs-devbase:504
  cache:
    paths:
      - .tox
  before_script:
    - apt-get -q --assume-yes build-dep .
    - apt-get -q --assume-yes install tox
  script:
    - tox
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: pytest.xml
    paths:
      - public/
    expire_in: 1 day

debian:
  interruptible: true
  image: gitregistry.knut.univention.de/univention/dist/ucs-ec2-tools
  before_script:
    - mkdir -p /var/log/apt
    - apt-get -qq update
    - apt-get -q --assume-yes build-dep .
  script:
    - dpkg-buildpackage --no-sign
    - mkdir -p artifacts
    - mv -t artifacts/ ../*.deb
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 day

docker:
  interruptible: true
  extends: .kaniko
  needs:
    - job: debian
  before_script:
    - cp Dockerfile artifacts/
  variables:
    KANIKO_BUILD_CONTEXT: artifacts
    KANIKO_ARGS: --cache=true --cache-repo=$CI_REGISTRY_IMAGE/cache
