include:
  - project: univention/dist/docker-services
    file: kaniko.yml

stages:
  - debian
  - docker

variables:
  LANG: "C.UTF-8"
  DEBIAN_FRONTEND: noninteractive
  CI_REGISTRY: docker-registry.knut.univention.de
  IMAGE_DEV: $CI_REGISTRY/ucs-ec2-tools

debian:
  stage: debian
  interruptible: true
  image: $IMAGE_DEV
  before_script:
    - mkdir -p /var/log/apt
    - apt-get -qq update
    - apt-get -q --assume-yes build-dep .
  script:
    - dpkg-buildpackage --no-sign
    - mkdir -p artifacts
    - mv -t artifacts/ ../*.deb
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 day

docker:
  stage: docker
  interruptible: true
  extends: .kaniko_knut
  dependencies:
    - debian
  before_script:
    - cp Dockerfile artifacts/
  variables:
    KANIKO_BUILD_CONTEXT: artifacts
    CI_REGISTRY_IMAGE: $CI_REGISTRY/ucs-vnc-tools
